version: 2
jobs:
  checkout:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: ls -al workspace
      - run: bash $PWD/scripts/checkout.sh /tmp/workspace 
      - run:
          name: List all changed authentic sources
          command: cat /tmp/workspace/changedSources.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - changedSources.txt
  expand-links:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: bash $PWD/scripts/expand.sh /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - bronnen/*
  push-to-repository:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "31:ea:38:19:fd:57:91:d2:16:94:e1:6a:19:20:36:1c"
      - run:
          name: Checkout target repository and branch
          workdir: /tmp
          command: |
            rm -rf werkgroep-authentieke-gegevensbronnen
            git clone git@github.com:ddvlanck/werkgroep-authentieke-gegevensbronnen.git
      - run:
          name: Checkout website branch
          workdir: /tmp/werkgroep-authentieke-gegevensbronnen
          command: |
            git checkout website
      - run:
          name: Clean the generated directory
          workdir: /tmp/werkgroep-authentieke-gegevensbronnen
          command: |
            git fetch origin
      - run:
          name: Copy generated assets
          workdir: /tmp/workspace
          command: |
            mkdir -p /tmp/werkgroep-authentieke-gegevensbronnen/content/
            cp -R bronnen/* /tmp/werkgroep-authentieke-gegevensbronnen/content/
       - run:
          name: Insert the commit on website branch
          command: |
            export TAG=`echo "${CIRCLE_SHA1}"`
            echo "{\"commit\" : \"$TAG\"}" > /tmp/werkgroep-authentieke-gegevensbronnen/commit.json
      - run:
          name: Push results to Github on 'website' branch
          workdir: /tmp/werkgroep-authentieke-gegevensbronnen
          command: |
            git config user.email "oslo@oslo"
            git config user.name "Circle CI Builder"
            git add .
            git status
            git commit -m "Applying changes from commit ${CIRCLE_SHA1}" --allow-empty
            git push --force origin website
workflows:
  version: 2
  agb_registry:
    jobs:
      - checkout
      - expand-links:
          requires:
            - checkout
      - push-to-repository:
          requires:
            - expand-links