version: 2
jobs:
  create-content:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: ls -al workspace
      - run:
          name: Completing the configuration files
          command: bash $PWD/scripts/create-content.sh /tmp/workspace https://github.com/ddvlanck/werkgroep-authtentieke-gegevensbronnen/tree/register
      - run:
          name: Listing all directories and files that have been created
          command: ls -al /tmp/workspace/*
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - bronnen/
            - commit.json
    push-to-repository:
      docker:
        - image: circleci/node
      steps:
        - checkout
        - attach_workspace:
            at: /tmp/workspace
        - add_ssh_keys:
            fingerprints:
              - "TODO"
        - run:
            name: Switch to 'website' branch in repository
            command: |
              git checkout website